name = "vesti"
grammar = "vesti"
path_suffixes = ["ves"]
line_comments = ["% "]

brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "$", end = "$", close = true, newline = true },
]
